name: Build and Deploy
run-name: Workflow run for ${{ github.ref }}
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      aws-deploy:
        type: boolean
        required: true
        default: false
jobs:
  build-telemetry-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/telemetry-service:${{ github.ref_name }}
